# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='books',
            old_name='desc',
            new_name='author',
        ),
    ]
